import type {
  Guest,
  Invitation,
  Plan,
  Template,
  User,
  Wedding,
  Wish,
} from "@/types";

export const HERO_IMAGE =
  "https://images.unsplash.com/photo-1519741497674-611481863552?w=1200&q=80";
export const HERO_IMAGE_2 =
  "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=800&q=80";
export const STORY_IMAGE =
  "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=600&q=80";
export const VENUE_IMAGE =
  "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=600&q=80";

export const DEMO_USER: User = {
  id: "user-1",
  email: "anna@example.com",
  name: "Анна Иванова",
  role: "organizer",
  plan: "premium",
  avatar: "https://i.pravatar.cc/100?u=anna",
  createdAt: "2025-01-15T10:00:00Z",
};

export const ADMIN_USER: User = {
  id: "admin-1",
  email: "admin@withlove.app",
  name: "Екатерина",
  role: "admin",
  plan: "lux",
  avatar: "https://i.pravatar.cc/100?u=ekaterina",
  createdAt: "2024-01-01T10:00:00Z",
};

export const DEMO_WEDDING: Wedding = {
  id: "wedding-1",
  userId: "user-1",
  coupleNames: "Александр и Екатерина",
  partner1: "Александр",
  partner2: "Екатерина",
  date: "2025-06-20T15:00:00",
  venue: 'Усадьба «Морозки»',
  venueAddress: "Московская область, Истринский р-н, д. Морозки, ул. Центральная, 1",
  guestCount: 120,
  status: "published",
};

export const DEMO_INVITATION: Invitation = {
  id: "inv-1",
  weddingId: "wedding-1",
  slug: "aleksandr-ekaterina",
  title: "Александр & Екатерина",
  templateId: "classic-1",
  published: true,
  publishedAt: "2025-03-01T12:00:00Z",
  views: 342,
  watermark: false,
  config: {
    theme: "classic",
    colors: {
      primary: "#E8A09A",
      accent: "#D4A537",
      background: "#FAF7F2",
      text: "#282B2B",
    },
    fonts: {
      heading: "Playfair Display",
      body: "Inter",
    },
    music: {
      enabled: true,
      trackName: "All of Me — John Legend",
      trackUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
      autoplay: true,
    },
    blocks: [
      {
        id: "b-hero",
        type: "hero",
        enabled: true,
        order: 0,
        data: {
          partner1: "Александр",
          partner2: "Екатерина",
          date: "2025-06-20",
          tagline: "Мы женимся!",
          image: HERO_IMAGE,
          cta: "Подтвердить участие",
        },
      },
      {
        id: "b-countdown",
        type: "countdown",
        enabled: true,
        order: 1,
        data: { targetDate: "2025-06-20T15:00:00" },
      },
      {
        id: "b-location",
        type: "location",
        enabled: true,
        order: 2,
        data: {
          name: 'Усадьба «Морозки»',
          address:
            "Московская область, Истринский р-н, д. Морозки, ул. Центральная, 1",
          mapUrl: "https://yandex.ru/maps/",
        },
      },
      {
        id: "b-transfer",
        type: "transfer",
        enabled: true,
        order: 3,
        data: {
          text: "Будет организован трансфер от м. Тушинская в 14:00. Обратно — в 00:30",
        },
      },
      {
        id: "b-schedule",
        type: "schedule",
        enabled: true,
        order: 4,
        data: {
          items: [
            { time: "16:00", title: "Сбор гостей", icon: "users" },
            { time: "16:30", title: "Церемония", icon: "heart" },
            { time: "17:00", title: "Фуршет и общение", icon: "glass" },
            { time: "18:30", title: "Банкет и поздравления", icon: "utensils" },
            { time: "21:00", title: "Первый танец и вечеринка", icon: "music" },
            { time: "23:30", title: "Торт и завершение", icon: "cake" },
          ],
        },
      },
      {
        id: "b-story",
        type: "story",
        enabled: true,
        order: 5,
        data: {
          title: "Наша история",
          text: "Мы познакомились в путешествии, влюбились с первого взгляда и больше не расставались. Каждый день с тех пор — маленькое приключение.",
          image: STORY_IMAGE,
        },
      },
      {
        id: "b-dresscode",
        type: "dresscode",
        enabled: true,
        order: 6,
        data: {
          text: "Будем рады видеть джентльменов в костюмах, а дам — в вечерних нарядах пастельных оттенков.",
          colors: ["#C98B88", "#A7B8A1", "#D4A537", "#F2EDE6", "#8B7355"],
        },
      },
      {
        id: "b-rsvp",
        type: "rsvp",
        enabled: true,
        order: 7,
        data: {
          deadline: "2025-05-20",
          title: "Подтвердите, пожалуйста, ваше присутствие",
        },
      },
      {
        id: "b-wishes",
        type: "wishes",
        enabled: true,
        order: 8,
        data: {
          title: "Пожелания",
          text: "Ваши тёплые слова будут самым ценным подарком.",
        },
      },
      {
        id: "b-faq",
        type: "faq",
        enabled: true,
        order: 9,
        data: {
          items: [
            {
              question: "Можно ли с детьми?",
              answer:
                "Да, дети приветствуются. На площадке будет детская зона и аниматор.",
            },
            {
              question: "Какой дресс-код?",
              answer:
                "Пастельные оттенки, smart casual. Избегайте белого и слишком ярких неоновых цветов.",
            },
            {
              question: "Как добраться?",
              answer:
                "Организован трансфер от м. Тушинская. Также можно на автомобиле — парковка бесплатная.",
            },
          ],
        },
      },
      {
        id: "b-gifts",
        type: "gifts",
        enabled: true,
        order: 10,
        data: {
          title: "Подарки",
          text: "Если вы хотите сделать нам подарок, будем благодарны за вклад в наше путешествие.",
        },
      },
      {
        id: "b-music",
        type: "music",
        enabled: true,
        order: 11,
        data: {
          title: "Музыка",
          text: "Поделитесь треками, которые хотите услышать на нашем празднике",
          trackName: "All of Me — John Legend",
        },
      },
      {
        id: "b-afterparty",
        type: "afterparty",
        enabled: false,
        order: 12,
        data: {
          title: "После свадьбы",
          text: "Приглашаем на after party на следующий день — brunch у бассейна с 12:00.",
        },
      },
      {
        id: "b-seating",
        type: "seating",
        enabled: false,
        order: 13,
        data: {
          title: "Рассадка гостей",
          text: "Найдите своё место за праздничным столом — схема появится ближе к дате.",
        },
      },
      {
        id: "b-payment",
        type: "payment",
        enabled: false,
        order: 14,
        data: {
          title: "Оплата",
          text: "Поддержите наш праздник удобным способом",
          recipient: "Александр И.",
        },
      },
    ],
  },
};

export const DEMO_GUESTS: Guest[] = [
  {
    id: "g1",
    weddingId: "wedding-1",
    name: "Мария Смирнова",
    email: "maria@example.com",
    status: "confirmed",
    plusOnes: 1,
    children: 0,
    side: "bride",
    table: "Стол 3",
    respondedAt: "2025-03-10T14:00:00Z",
  },
  {
    id: "g2",
    weddingId: "wedding-1",
    name: "Иван Петров",
    email: "ivan@example.com",
    status: "confirmed",
    plusOnes: 0,
    children: 0,
    side: "groom",
    table: "Стол 1",
    respondedAt: "2025-03-11T10:00:00Z",
  },
  {
    id: "g3",
    weddingId: "wedding-1",
    name: "Ольга Сергеева",
    status: "pending",
    plusOnes: 0,
    children: 2,
    side: "bride",
  },
  {
    id: "g4",
    weddingId: "wedding-1",
    name: "Дмитрий Кузнецов",
    status: "declined",
    plusOnes: 0,
    children: 0,
    side: "groom",
    message: "К сожалению, буду в командировке",
    respondedAt: "2025-03-12T09:00:00Z",
  },
  {
    id: "g5",
    weddingId: "wedding-1",
    name: "Елена Волкова",
    email: "elena@example.com",
    status: "confirmed",
    plusOnes: 1,
    children: 1,
    dietary: "Вегетарианское меню",
    side: "bride",
    table: "Стол 4",
    respondedAt: "2025-03-13T16:00:00Z",
  },
  {
    id: "g6",
    weddingId: "wedding-1",
    name: "Сергей Морозов",
    status: "maybe",
    plusOnes: 0,
    children: 0,
    side: "groom",
  },
  {
    id: "g7",
    weddingId: "wedding-1",
    name: "Анна Морозова",
    status: "confirmed",
    plusOnes: 0,
    children: 0,
    side: "bride",
    table: "Стол 2",
    message: "С нетерпением ждём!",
    respondedAt: "2025-03-14T11:00:00Z",
  },
  {
    id: "g8",
    weddingId: "wedding-1",
    name: "Павел Новиков",
    status: "pending",
    plusOnes: 1,
    children: 0,
    side: "groom",
  },
];

export const DEMO_WISHES: Wish[] = [
  {
    id: "w1",
    invitationId: "inv-1",
    authorName: "Мария",
    text: "Желаем вам любви, тепла и бесконечного счастья! Пусть каждый день будет как свадебный ❤️",
    createdAt: "2025-03-15T12:00:00Z",
  },
  {
    id: "w2",
    invitationId: "inv-1",
    authorName: "Иван и Катя",
    text: "Дорогие друзья! Поздравляем с этим прекрасным днём. Будьте счастливы вместе!",
    createdAt: "2025-03-16T18:00:00Z",
  },
];

export const TEMPLATES: Template[] = [
  {
    id: "classic-1",
    name: "Классика",
    nameEn: "Classic",
    style: "classic",
    category: "Классика",
    premium: false,
    price: 0,
    preview: HERO_IMAGE,
    colors: ["#FAF7F2", "#C98B88", "#D4A537"],
    description: "Элегантный классический стиль с флористикой",
    descriptionEn: "Elegant classic style with florals",
  },
  {
    id: "minimal-1",
    name: "Минимализм",
    nameEn: "Minimal",
    style: "minimal",
    category: "Минимализм",
    premium: false,
    price: 0,
    preview: HERO_IMAGE_2,
    colors: ["#FFFFFF", "#282B2B", "#A7B8A1"],
    description: "Чистые линии, много воздуха, сдержанная эстетика",
    descriptionEn: "Clean lines, lots of space, restrained aesthetic",
  },
  {
    id: "botanic-1",
    name: "Ботаника",
    nameEn: "Botanic",
    style: "botanic",
    category: "Ботаника",
    premium: true,
    price: 1990,
    preview:
      "https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=600&q=80",
    colors: ["#E8EDE5", "#A7B8A1", "#5C6B55"],
    description: "Зелень, природные мотивы, свежесть",
    descriptionEn: "Greenery, natural motifs, freshness",
  },
  {
    id: "luxury-1",
    name: "Роскошь",
    nameEn: "Luxury",
    style: "luxury",
    category: "Роскошь",
    premium: true,
    price: 2990,
    preview:
      "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=600&q=80",
    colors: ["#111111", "#D4A537", "#1A1A1A"],
    description: "Чёрно-золотая палитра, утончённая типографика",
    descriptionEn: "Black and gold palette, refined typography",
  },
  {
    id: "travel-1",
    name: "Путешествия",
    nameEn: "Travel",
    style: "travel",
    category: "Путешествия",
    premium: true,
    price: 2490,
    preview:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80",
    colors: ["#FDF9F3", "#4A90A4", "#D4A537"],
    description: "Для торжеств в других странах и на побережье",
    descriptionEn: "For celebrations abroad and by the coast",
  },
  {
    id: "rustic-1",
    name: "Рустик",
    nameEn: "Rustic",
    style: "rustic",
    category: "Рустик",
    premium: true,
    price: 1990,
    preview:
      "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=600&q=80",
    colors: ["#F2EDE6", "#8B7355", "#C98B88"],
    description: "Тёплый, уютный стиль с природными акцентами",
    descriptionEn: "Warm, cozy style with natural accents",
  },
  {
    id: "lavender-1",
    name: "Лавандовый сад",
    nameEn: "Lavender Garden",
    style: "classic",
    category: "Классика",
    premium: true,
    price: 1990,
    preview:
      "https://images.unsplash.com/photo-1478144592103-25e218a04891?w=600&q=80",
    colors: ["#F8E8E8", "#B8A9C9", "#D4A537"],
    description: "Нежные лавандовые тона и романтика",
    descriptionEn: "Soft lavender tones and romance",
  },
  {
    id: "scandi-1",
    name: "Скандинавский",
    nameEn: "Scandinavian",
    style: "minimal",
    category: "Минимализм",
    premium: false,
    price: 0,
    preview:
      "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=600&q=80",
    colors: ["#FAF7F2", "#A7B8A1", "#282B2B"],
    description: "Минимализм, светлые тона, естественный свет",
    descriptionEn: "Minimalism, light tones, natural light",
  },
  {
    id: "garden-1",
    name: "Свадьба в саду",
    nameEn: "Garden Wedding",
    style: "botanic",
    category: "Ботаника",
    premium: true,
    price: 2490,
    preview:
      "https://images.unsplash.com/photo-1460978812857-470ed1c77af0?w=600&q=80",
    colors: ["#FDF9F3", "#C98B88", "#A7B8A1"],
    description: "Цветочные мотивы, пастельные оттенки",
    descriptionEn: "Floral motifs, pastel shades",
  },
  {
    id: "save-date-1",
    name: "Save the Date",
    nameEn: "Save the Date",
    style: "classic",
    category: "Save-the-Date",
    premium: false,
    price: 0,
    preview:
      "https://images.unsplash.com/photo-1520854221256-17451cc331bf?w=600&q=80",
    colors: ["#FAF7F2", "#D4A537", "#C98B88"],
    description: "Анонсируйте дату стильно и с волнением",
    descriptionEn: "Announce the date stylishly",
  },
  {
    id: "engagement-1",
    name: "Помолвка",
    nameEn: "Engagement",
    style: "classic",
    category: "Помолвка",
    premium: true,
    price: 1490,
    preview:
      "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=600&q=80",
    colors: ["#F8E8E8", "#F76E62", "#D4A537"],
    description: "Поделитесь радостной новостью о помолвке",
    descriptionEn: "Share the joyful engagement news",
  },
  {
    id: "weekend-1",
    name: "Свадебный уикенд",
    nameEn: "Wedding Weekend",
    style: "travel",
    category: "Уикенд",
    premium: true,
    price: 2990,
    preview:
      "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=600&q=80",
    colors: ["#FDF9F3", "#4A90A4", "#D4A537"],
    description: "Полная программа мероприятий на несколько дней",
    descriptionEn: "Full multi-day event program",
  },
];

export const PLANS: Plan[] = [
  {
    id: "free",
    name: "Бесплатно",
    nameEn: "Free",
    price: 0,
    guestLimit: 30,
    watermark: true,
    features: [
      "Базовые шаблоны",
      "RSVP-форма",
      "До 30 гостей",
      "Водяной знак With Love",
      "Таймер и локация",
    ],
    featuresEn: [
      "Basic templates",
      "RSVP form",
      "Up to 30 guests",
      "With Love watermark",
      "Countdown & location",
    ],
  },
  {
    id: "basic",
    name: "Базовый",
    nameEn: "Basic",
    price: 2490,
    guestLimit: 50,
    watermark: true,
    features: [
      "Все функции Free",
      "Больше шаблонов",
      "Поддержка на email",
      "До 50 гостей",
      "Пожелания гостей",
    ],
    featuresEn: [
      "All Free features",
      "More templates",
      "Email support",
      "Up to 50 guests",
      "Guest wishes",
    ],
  },
  {
    id: "premium",
    name: "Премиум",
    nameEn: "Premium",
    price: 4990,
    popular: true,
    guestLimit: 150,
    watermark: false,
    features: [
      "Все функции Базового",
      "RSVP в реальном времени",
      "Без водяного знака",
      "До 150 гостей",
      "Фоновая музыка",
      "Экспорт гостей CSV",
    ],
    featuresEn: [
      "All Basic features",
      "Real-time RSVP",
      "No watermark",
      "Up to 150 guests",
      "Background music",
      "Guest CSV export",
    ],
  },
  {
    id: "lux",
    name: "Люкс",
    nameEn: "Lux",
    price: 7990,
    guestLimit: 500,
    watermark: false,
    features: [
      "Все функции Премиум",
      "Персональный менеджер",
      "Расширенная аналитика",
      "До 500 гостей",
      "Кастомные цвета",
      "Приоритетная поддержка",
    ],
    featuresEn: [
      "All Premium features",
      "Personal manager",
      "Advanced analytics",
      "Up to 500 guests",
      "Custom colors",
      "Priority support",
    ],
  },
];

export const FEATURES = [
  {
    id: "rsvp",
    icon: "heart",
    title: "RSVP",
    titleEn: "RSVP",
    desc: "Удобный сбор ответов гостей",
    descEn: "Easy guest response collection",
  },
  {
    id: "timer",
    icon: "clock",
    title: "Таймер",
    titleEn: "Countdown",
    desc: "Обратный отсчёт до свадьбы",
    descEn: "Countdown to the wedding",
  },
  {
    id: "transfer",
    icon: "car",
    title: "Трансфер",
    titleEn: "Transfer",
    desc: "Организация трансфера",
    descEn: "Transfer organization",
  },
  {
    id: "story",
    icon: "book",
    title: "Love story",
    titleEn: "Love story",
    desc: "Ваша история любви",
    descEn: "Your love story",
  },
  {
    id: "music",
    icon: "music",
    title: "Музыка",
    titleEn: "Music",
    desc: "Плейлист для гостей",
    descEn: "Playlist for guests",
  },
  {
    id: "seating",
    icon: "users",
    title: "Рассадка гостей",
    titleEn: "Seating",
    desc: "Схема рассадки",
    descEn: "Seating chart",
  },
  {
    id: "templates",
    icon: "layout",
    title: "Шаблоны",
    titleEn: "Templates",
    desc: "Стильные дизайны",
    descEn: "Stylish designs",
  },
  {
    id: "payment",
    icon: "credit-card",
    title: "Онлайн-оплата",
    titleEn: "Payments",
    desc: "Приём подарков онлайн",
    descEn: "Accept gifts online",
  },
];

export const LANDING_FAQ = [
  {
    q: "Как быстро я могу создать приглашение?",
    qEn: "How quickly can I create an invitation?",
    a: "Большинство пар создают и публикуют приглашение за 10–15 минут. Выберите шаблон, заполните данные — и готово.",
    aEn: "Most couples create and publish in 10–15 minutes. Pick a template, fill in details — done.",
  },
  {
    q: "Могут ли гости ответить без регистрации?",
    qEn: "Can guests RSVP without registration?",
    a: "Да. Гости открывают ссылку и заполняют простую форму — без аккаунтов и приложений.",
    aEn: "Yes. Guests open the link and fill a simple form — no accounts or apps needed.",
  },
  {
    q: "Как работает онлайн-оплата?",
    qEn: "How do online payments work?",
    a: "Вы можете добавить блок с реквизитами или ссылкой на сбор подарков. Средства приходят напрямую вам.",
    aEn: "You can add payment details or a gift fund link. Funds go directly to you.",
  },
  {
    q: "Можно ли изменить текст после публикации?",
    qEn: "Can I edit after publishing?",
    a: "Конечно. Редактируйте блоки в любое время — изменения сразу появятся на опубликованной странице.",
    aEn: "Absolutely. Edit blocks anytime — changes appear instantly on the live page.",
  },
];

export const REVIEWS = [
  {
    name: "Аня и Максим",
    text: "Сделали приглашение за вечер. Гости в восторге, а мы — от удобной статистики ответов.",
    textEn: "Made the invitation in one evening. Guests loved it, and we loved the RSVP stats.",
    rating: 5,
    avatar: "https://i.pravatar.cc/80?u=anya",
  },
  {
    name: "Ксения и Артём",
    text: "Красиво, минималистично, удобно. Особенно понравился таймер и блок с трансфером.",
    textEn: "Beautiful, minimal, convenient. Especially loved the countdown and transfer block.",
    rating: 5,
    avatar: "https://i.pravatar.cc/80?u=ksenia",
  },
  {
    name: "Дарья и Никита",
    text: "Очень приятный дизайн и удобный конструктор. Все вопросы гостей закрыли одним сайтом.",
    textEn: "Lovely design and easy builder. One site answered all guest questions.",
    rating: 5,
    avatar: "https://i.pravatar.cc/80?u=darya",
  },
];
